# Generated by Django 2.2.17 on 2021-01-13 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210113_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='activation_key_exires',
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 14, 48, 54, 784904, tzinfo=utc)),
        ),
    ]
