# Generated by Django 2.2.17 on 2021-02-01 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_auto_20210122_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 10, 37, 16, 736551, tzinfo=utc)),
        ),
    ]
